config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'welcome/index'

  get 'profile/:id', to: 'profile#show_profile'

  get 'properties/show_json/:id', to: 'properties#show_json'

  post 'properties/search'

  post 'properties/edit'

  get 'profile/:id/edit_profile', to: 'profile#edit_profile'

  resources :properties

  get '/auth/:provider/callback', to: 'sessions#create'

  post 'sessions/get_user'

  post 'properties/create_android'

  get '/profile/json/:id', to: 'profile#show_profile_json'

  delete '/logout', to: 'sessions#destroy'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  get '/conversations', to: 'conversations#index'

  post '/conversations/index_json'

  resources :messages, only: [:new, :create]

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)   
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name}</option>"
    end
    s.html_safe
  end
end

app/views/messages/new.html.erb
<% page_header "Start Conversation" %>

<%= form_tag messages_path, method: :post do %>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'recipients', 'Choose recipients' %>
    <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>