config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'welcome/index'

  get 'profile/:id', to: 'profile#show_profile'

  get 'properties/show_json/:id', to: 'properties#show_json'

  post 'properties/search'

  post 'properties/edit'

  get 'profile/:id/edit_profile', to: 'profile#edit_profile'

  resources :properties

  get '/auth/:provider/callback', to: 'sessions#create'

  post 'sessions/get_user'

  post 'properties/create_android'

  get '/profile/json/:id', to: 'profile#show_profile_json'

  delete '/logout', to: 'sessions#destroy'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  get '/conversations', to: 'conversations#index'

  post '/conversations/index_json'

  resources :messages, only: [:new, :create]

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # Mailboxer actions
  before_action :get_mailbox, except: [:index_json]
  before_action :get_conversation, except: [:index, :index_json]
  # CSRF controls (may the gods have mercy on my soul)
  skip_before_action :verify_authenticity_token, only: [:index_json]

  def index
    if current_user == nil
      redirect_to root_path, flash: {error: "You need to be logged in to do that!"}
    else
      @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
    end
  end

  def index_json
    userid = params[:id]
    user = User.where(:uid => userid)[0]
    @conversations = user.mailbox.conversations(user)
    puts @conversations[0].messages[0].inspect
  end

  def show
    current_user.mark_as_read(@conversation)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end

  def avatar_for(user)
    image_tag user.image_url, alt: user.first_name
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>
  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <% if conversation.last_message.sender == current_user %>
    <%= avatar_for conversation.last_message.recipients[0] %>
  <% else %>
    <%= avatar_for conversation.last_message.sender %>

  <p><%= conversation.last_message.body %>
    <% end %>
    <small>
      <span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>
    </small>
  </p>

</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= avatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<% page_header "Your Conversations" %>

<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>

<ul class="list-group">
  <%= render partial: 'conversations/conversation', collection: @conversations %>
</ul>

<%= will_paginate %>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <% message = receipt.message %>
        <div class="media-left">
            <%= avatar_for message.sender %>
          </div>

        <%= message.sender.first_name %>
          says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
        <%= message.body %>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>