config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'welcome/index'

  get 'profile/:id', to: 'profile#show_profile'

  get 'properties/show_json/:id', to: 'properties#show_json'

  post 'properties/search'

  post 'properties/edit'

  get 'profile/:id/edit_profile', to: 'profile#edit_profile'

  resources :properties

  get '/auth/:provider/callback', to: 'sessions#create'

  post 'sessions/get_user'

  post 'properties/create_android'

  get '/profile/json/:id', to: 'profile#show_profile_json'

  delete '/logout', to: 'sessions#destroy'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  get '/conversations', to: 'conversations#index'

  post '/conversations/index_json'

  resources :messages, only: [:new, :create]

end

app/models/property.rb
class Property < ApplicationRecord
  # Database associations
  belongs_to :landlord, class_name: 'User', foreign_key: "uid"
  belongs_to :tenant, class_name: 'User', optional: true

  # Paperclip gem assertions
  @hash = ENV["HASH_SEED"]
  has_attached_file :image1, url: "/photos/:hash.:extension", hash_secret: @hash
  has_attached_file :image2, url: "/photos/:hash.:extension", hash_secret: @hash
  has_attached_file :image3, url: "/photos/:hash.:extension", hash_secret: @hash
  has_attached_file :image4, url: "/photos/:hash.:extension", hash_secret: @hash
  validates_attachment :image1, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  validates_attachment :image2, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  validates_attachment :image3, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  validates_attachment :image4, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  # Method to search database for properties meeting criteria
  def self.search(criteria)
    # local variables
    wildcard = '%'
    max_price = 10_000_000
    max_rooms = 100
    max_sqm   = 10_000

    puts criteria

    # check for empty values from the frontend and give them default
    # values

    criteria['zipcode'] = wildcard if criteria['zipcode'] == ''

    criteria['price_min'] = 0 if criteria['price_min'] == ''

    criteria['price_max'] = max_price if criteria['price_max'] == ''

    criteria['rooms_min'] = 0 if criteria['rooms_min'] == ''

    criteria['rooms_max'] = max_rooms if criteria['rooms_max'] == ''

    criteria['rooms_max'] = max_rooms if criteria['rooms_max'] == '7'

    criteria['property_type'] = wildcard if criteria['property_type'] == ''

    criteria['square_meters_min'] = 0 if criteria['square_meters_min'] == '0'

    criteria['square_meters_max'] = max_sqm if criteria['square_meters_max'] == '0'


    # fetch proper where statement
    if criteria['zipcode'] == wildcard && criteria['property_type'] == wildcard
        where(
            'zipcode ILIKE ? AND (price >= ? AND price <= ?) AND (num_bedrooms >= ? AND num_bedrooms <= ? ) AND (size >= ? AND size <= ?) AND property_type ILIKE ?',
            criteria['zipcode'], criteria['price_min'], criteria['price_max'],
            criteria['rooms_min'], criteria['rooms_max'], criteria['square_meters_min'],
            criteria['square_meters_max'], criteria['property_type']
        )
    elsif criteria['zipcode'] == wildcard
      where(
          'zipcode ILIKE ? AND (price >= ? AND price <= ?) AND (num_bedrooms >= ? AND num_bedrooms <= ? ) AND (size >= ? AND size <= ?) AND property_type IN (?)',
          criteria['zipcode'], criteria['price_min'], criteria['price_max'],
          criteria['rooms_min'], criteria['rooms_max'], criteria['square_meters_min'],
          criteria['square_meters_max'], criteria['property_type']
      )
    elsif criteria['property_type'] == wildcard
      where(
          'zipcode IN (?) AND (price >= ? AND price <= ?) AND (num_bedrooms >= ? AND num_bedrooms <= ? ) AND (size >= ? AND size <= ?) AND property_type ILIKE ?',
          criteria['zipcode'], criteria['price_min'], criteria['price_max'],
          criteria['rooms_min'], criteria['rooms_max'], criteria['square_meters_min'],
          criteria['square_meters_max'], criteria['property_type']
      )
    else
        where(
            'zipcode IN (?) AND (price >= ? AND price <= ?) AND (num_bedrooms >= ? AND num_bedrooms <= ? ) AND (size >= ? AND size <= ?) AND property_type IN (?)',
            criteria['zipcode'], criteria['price_min'], criteria['price_max'],
            criteria['rooms_min'], criteria['rooms_max'], criteria['square_meters_min'],
            criteria['square_meters_max'], criteria['property_type']
        )
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    skip_before_action :verify_authenticity_token


    # Handler for creating property listings and saving to database
    def create
        @property = Property.new(property_params)
        @property.landlord = current_user

        @property.save
        redirect_to @property
    end

    def destroy
      @property = Property.find(params[:id])
      @property.destroy
      redirect_to action: "show_profile", controller: "profile", id: current_user.id
    end

    # Handler for dealing with request to edit property
    def edit
      @property_to_edit = Property.find(params[:id])
      if @property_to_edit.landlord != current_user
        redirect_to root_path
      end
    end

    def index
    end

    # Handler for request to create new property in database
    def new
      if !(current_user.present?)
        redirect_to root_path, flash: {error: "You need to be logged in to create listings"}
      end
    end


    def search
        @search = params[:search]
        if @search
            puts 'Search parameters:'
            puts @search.inspect
            puts @search['zipcode']
            @properties = Property.search(params[:search]).order('created_at DESC')
        else
          @properties = Property.all
        end
    end

    def show_json
        @property = Property.find(params[:id])
    end

    def show
      if !(current_user.present?)
        redirect_to root_path, flash: {error: "Þú þarft að vera skráð(ur) inn!"}
      end

      begin
        @property = Property.find(params[:id])
      rescue
        redirect_to root_path, flash: {error: "Property does not exist"}
      end
    end

    def update
      @property_to_update = Property.find(params[:id])
      if @property_to_update.update_attributes(property_params)
        redirect_to(:action => 'show')
      else
        redirect_to(root_path)
      end
    end


    def create_android
      userid = params[:id]
      @property = Property.new(property_params)
      @property.landlord = User.where(:uid => userid)[0]

      @property.save

      @property

      puts @property.address

      redirect_to action: "show_json", id: @property.id
    end

    private
    # Private method for database validation
    def property_params
        params.require(:property).permit(:address, :zipcode, :city, :price,
          :size, :num_bedrooms, :num_bathrooms, :property_type, :lat, :lon,
          :image1, :image2, :image3, :image4, :description)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/edit.html.erb
<div class="leftContainer container">
<h2>Breyttu upplýsingum</h2>

<%= form_for @property_to_edit do |f| %>

<div class="flexContainer">

  <div class="flexChild">
<p>
    <%= f.label :address, "Heimilisfang" %>
    <br>
    <%= f.text_field :address %>
</p>

<p>
    <%= f.label :zipcode, "Póstnúmer" %>
    <br>
    <%= f.text_field :zipcode %>
</p>

<p>
    <%= f.label :city, "Borg/bær" %>
    <br>
    <%= f.text_field :city %>
</p>

<p>
    <%= f.label :price, "Leigurverð" %>
    <br>
    <%= f.text_field :price %>
</p>

<p>
    <%= f.label :size, "Fermetrar" %>
    <br>
    <%= f.text_field :size %>
</p>

</div>
<div class="flexChild">

<p>
    <%= f.label :num_bedrooms, "Fjöldi svefnherbergja" %>
    <br>
    <%= f.text_field :num_bedrooms %>
</p>

<p>
    <%= f.label :num_bathrooms, "Fjöldi baðherbergja" %>
    <br>
    <%= f.text_field :num_bathrooms %>
</p>

<p>
    <%= f.label :property_type, "Tegund húsnæðis" %>
    <br>
    <%= f.select(:property_type,
    options_for_select([['Einbýlishús', 'Einbýlishús'],
    ['Fjölbýlishús', 'Fjölbýlishús'],
    ['Parhús', 'Fjölbýlishús']])) %>
</p>

<p>
  <%= f.label :lat, "Latitude" %>
    <br>
    <%= f.text_field :lat %>
</p>

<p>
  <%= f.label :lon, "Longitude" %>
    <br>
    <%= f.text_field :lon %>
</p>
</div>

</div>

<p id="submitButton">
    <%= f.submit  "Uppfæra"%>
</p>

<%= link_to 'Eyða', @property_to_edit, method: :delete, confirm: "This cannot be undone" %>

<% end %>
</div>

<div class="rightContainer container">
    <div id="map"></div>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8qF171O_qBdXdwSLnH07kFDtbCk5M1CY&callback=initNewPropertyMap"></script>
</div>

app/views/properties/new.html.erb
<div class="leftContainer container">
  <div id="porpertyListingTitle">
    <h1>Vinsamlegast fyllið út eftirfarandi form</h1>
  </div>

  <%= form_for :property, url: properties_path do |f| %>
<div class="flexContainer">
  <div class="flexChild">

    <p>
        <%= f.label :address, "Heimilisfang" %>
        <br>
        <%= f.text_field :address %>
    </p>

    <p>
        <%= f.label :zipcode, "Póstnúmer" %>
        <br>
        <%= f.text_field :zipcode %>
    </p>

    <p>
        <%= f.label :city, "Borg/Bær" %>
        <br>
        <%= f.text_field :city %>
    </p>

    <p>
        <%= f.label :price, "Leiguverð" %>
        <br>
        <%= f.text_field :price %>
    </p>

    <p>
        <%= f.label :size, "Fermetrar" %>
        <br>
        <%= f.text_field :size %>
    </p>

    <p>
        <%= f.label :num_bedrooms, "Fjöldi svefnherbergja" %>
        <br>
        <%= f.text_field :num_bedrooms %>
    </p>

    <p>
        <%= f.label :num_bathrooms, "Fjöldi baðherbergja" %>
        <br>
        <%= f.text_field :num_bathrooms %>
    </p>

  </div>
  <div class="flexChild">

    <p>
        <%= f.label :property_type, "Tegund húsnæðis" %>
        <br>
        <%= f.select(:property_type,
        options_for_select([['Einbýlishús', 'Einbýlishús'],
        ['Fjölbýlishús', 'Fjölbýlishús'],
        ['Parhús', 'Fjölbýlishús']])) %>
    </p>

    <p class="hiddenInput">
      <%= f.label :lat, "Latitude" %>
        <br>
        <%= f.text_field :lat %>
    </p>

    <p class="hiddenInput">
      <%= f.label :lon, "Longitude" %>
        <br>
        <%= f.text_field :lon %>
    </p>

    <p>
      <%= f.label :image1, "Forsíðumynd" %>
        <br>
        <%= f.file_field :image1 %>
    </p>

    <p>
      <%= f.label :image2, "Mynd 2" %>
        <br>
        <%= f.file_field :image2 %>
    </p>

    <p>
      <%= f.label :image3, "Mynd 3" %>
        <br>
        <%= f.file_field :image3 %>
    </p>

    <p>
      <%= f.label :image4, "Mynd 4" %>
        <br>
        <%= f.file_field :image4 %>
    </p>

    <h2>Vinsamlegast smellið á kortið til hægri til að
    sýna staðsetningu á eigninni</h2>

  </div>

</div>

  <p id="newDescription">
      <%= f.label :description, "Lýsing" %>
      <br>
      <%= f.text_area :description, rows: "15" %>
  </p>

  <p>
      <%= f.submit  %>
  </p>

  <% end %>

</div>

<div class="rightContainer container">
    <div id="map"></div>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8qF171O_qBdXdwSLnH07kFDtbCk5M1CY&callback=initNewPropertyMap"></script>
</div>

app/views/properties/show.html.erb
<div class="leftContainer container">

<div class="flexContainerTitle">
  <% if @property.image1? %>
   <img src="<%= @property.image1.url %>" class="mainImageShow imageClick"/>
  <% end %>
  <div id="propertyTitle">
    <h1 class="addressTitle"><%= @property.address %></h1>
    <h2>Leiguverð</h2>
    <p><%= number_with_delimiter(@property.price, delimiter: ".") %></p>
    <h2>Leigusali</h2>
    <a href="/profile/<%= @property.landlord.id %>" > <%= @property.landlord.first_name %> <%= @property.landlord.last_name %></a>
  </div>

</div>

<div class="flexContainer">
  <div class="flexChild">
    <div>
        <h3>Póstnúmer</h3>
        <p><%= @property.zipcode  %></p>
    </div>

    <div>
        <h3>Borg/Bær</h3>
        <p><%= @property.city %></p>
    </div>

    <div>
        <h3>Fermetrar</h3>
        <p><%= @property.size %></p>
    </div>
  </div>

  <div class="flexChild">
    <div>
        <h3>Fjöldi svefnherbergja</h3>
        <p><%= @property.num_bedrooms %></p>
    </div>

    <div>
        <h3>Fjöldi barherbergja</h3>
        <p><%= @property.num_bathrooms %></p>
    </div>

    <div>
        <h3>Tegund húsnæðis</h3>
        <p><%= @property.property_type %></p>
    </div>
  </div>

  <div id="propertyShowDesc" lat= <%= @property.lat %> lng= <%= @property.lon %>>
      <h3>Lýsing</h3>
      <p><%= @property.description %></p>
  </div>

</div>

<div class="flexContainerTitle">
<% if current_user.id == @property.landlord.id %>
  <h3>Þetta er þitt eigið húsnæði</h3>
  <%= link_to "Breyta/Eyða", edit_property_path(@property)%>
<% end %>
</div>
</div>

<div class="rightContainer container smallMapContainer">

    <div class="imageContainer">
      <div class="imageDisplay imageClick">
        <% if @property.image2? %>
          <img src="<%= @property.image2.url %>" class="sideImageShow"/>
          <span class="imageOverlay"><h2>STÆKKA</h2></span>
        <% else %>
          <h3>Engin mynd<h3>
        <% end %>
      </div>

      <div class="imageDisplay imageClick">
        <% if @property.image3? %>
          <img src="<%= @property.image3.url %>" class="sideImageShow"/>
          <span class="imageOverlay"><h2>STÆKKA</h2></span>
        <% else %>
          <h3>Engin mynd<h3>
        <% end %>
      </div>

      <div class="imageDisplay imageClick">
        <% if @property.image4? %>
          <img src="<%= @property.image4.url %>" class="sideImageShow"/>
          <span class="imageOverlay"><h2>STÆKKA</h2></span>
        <% else %>
          <h3>Engin mynd<h3>
        <% end %>
      </div>
    </div>

    <div class="smallMap">
      <div id="map"></div>
    </div>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8qF171O_qBdXdwSLnH07kFDtbCk5M1CY&callback=initShowPropertiesMap"></script>
</div>

<div class="imageShowcase">
  <img class="showcasedImage"/>
</div>